# Generated by Django 3.0.3 on 2022-03-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TradeParner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(choices=[('shipping', 'Shipping'), ('receiving', 'Receiving')], max_length=9)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Commodity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.TradeParner')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.TradeParner'),
        ),
    ]
