# Generated by Django 3.0.3 on 2022-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='details',
            field=models.CharField(max_length=2048),
        ),
    ]
